name: .NET

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      TEST: 'FigureArea/FigureArea/FigureArea.csproj'
      MAIN: 'FigureArea/FigureArea.Test/FigureArea.Test.csproj'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x


    - name: Restore dependencies
      run: dotnet restore $TEST

    - name: Build
      run: dotnet build $TEST --configuration $BUILD_CONFIG
      
    - name: Tests
      run: dotnet test $TEST --configuration $BUILD_CONFIG

    - name: Main function
      run: dotnet run --project $MAIN
